### ISSUE TITLE
Support other countries

### ISSUE THREAD

**Issue by accuracity** [accuracity/accuracity#4]
Support other countries.
Some first ideas:
- Europe: Capital + 3 biggest cities of each country
- US: State capitals (50) + add other big cities from top50/top100?
- Japan

**Comment by thuiop** [comment]
Having more French cities would be a good thing too ; otherwise you will have repetitions very fast. It has already been 3 days in a row with Rouen in the daily play... And even if you ensure they are spread out, it only takes 16 days to go through every city in the list.

This would be the same for Europe/US : you want to have more than 100 cities for each.

**Comment by accuracity** [comment]
Initially I tried to include the 1000 biggest cities of France but it was really hard!
However it could be a "very hard" or "hardcore" mode.
Also my idea was that the random will make usl learn day after day about most of the city, so it is ok to have them several times (but maybe in a few weeks everybody will become very good with most of the cities and then it will be a good time to add new cities).

**Comment by thuiop** [comment]
This could be a thing where in the daily mix you would have 3 "easy" cities, 10 "medium", 5 "hard" and 2 "very hard" (or other proportions of course).

**Comment by accuracity** [comment]
EU and US now included in branch `i18n\
